### ISSUE TITLE
[Suggestion]Add Substratum OMS 7.1 Support In Lineage os 

### ISSUE THREAD

**Issue by MASTERGUY** [divis1969/android_device_meizu_meilan2#125] opened 2017-05-15 06:14 UTC
not a issue :) but i want Substratum OMS 7.1 Support in Lineage os ;) If possible please Look over it 
Thanks for effort :)

**Comment by divis1969** [comment] 2017-05-17 11:03
Duplicate of #124

**Closed as completed by divis1969** 2017-05-17 11:03 UTC
