### ISSUE TITLE
Some sensors not working

### ISSUE THREAD

**Issue by sergibaljin** [divis1969/android_device_meizu_meilan2#74] opened 2016-07-29 19:03 UTC
Hi,
I just installed v0.11 and these sensors don't work:
- gyroscope
- orientation
- magnetometer

With the original rom they were OK.

I have attached the output of logcat while switching on the phone and the log of logcat *|E.
Please let me know how I can help and thanks for the amazing work.

[switchingon.txt](https://github.com/divis1969/android_device_meizu_meilan2/files/391164/switchingon.txt)
[error.txt](https://github.com/divis1969/android_device_meizu_meilan2/files/391165/error.txt)

**Comment by sergibaljin** [comment] 2016-07-29 22:19
As seen in #53 the magnetometer returns nothing even if the sensor seems recognized.
Tried with v0.10 and v0.11

**Comment by sergibaljin** [comment] 2016-08-02 12:42
Checking a bit things to understand what can be wrong.
Doing a "cat /sys/devices/msensor.51/driver/chipinfo", I get a "qmxX983 Chip"

the command "cat /sys/devices/msensor.51/driver/sensordata" returns "-949 -1951 1692"
Checking the cust_mag.57, in uevent, the output is:

OF_NAME=cust_mag
OF_FULL_NAME=/cust_mag@0
OF_COMPATIBLE_0=mediatek, AKM09911
OF_COMPATIBLE_N=1

Is that sensor included in the kernel of this ROM?
Sorry to bother.

**Comment by divis1969** [comment] 2016-08-02 14:26
The kernel image is a binary from 4.5.4I. Since you are checking sysfs which is provided by kernel modules, yes, this driver is included.
Actually, I cannot rely on this sysfs info: when I was playing with proximity, I found few places for this sensor from different drivers and this seems the root cause why some devices are not correctly handled by the code I'm using. Looks like either MTK or Meizu or both are using some proprietary code for sensors. This architecture is not clear for me.
The same could be applicable for mag.

**Comment by sergibaljin** [comment] 2016-08-02 20:53
Thanks for your reply.
I think our hardware is completely different, beside the logo on the cover.
If I can send you logs or any other info just let me know.

**Comment by divis1969** [comment] 2016-09-15 11:54
The issue, I hope is fixed with the changes https://github.com/divis1969/android_device_meizu_meilan2/commit/94ef726ee8cacc8687c7bd06f25ed20af9017d0b
https://github.com/divis1969/android_vendor_meizu_meilan2/commit/16db533987d20ad3ab98202257de075ad6358406

Could you please test v0.12?

**Comment by grozahn** [comment] 2016-09-16 04:55
Close

**Comment by sergibaljin** [comment] 2016-09-16 12:21
Hi,
Sensors work perfectly, thanks really a lot!
A semi-related question though: the phone doesn't deep sleep any more, I guess is the proximity sensor keeping the CPU busy (like in version .10 and .11). Can you suggest anything about that?

Thanks again for everything!

**Comment by divis1969** [comment] 2016-09-16 12:43
You can try to set the property as described here:
https://github.com/divis1969/android_frameworks_base/commit/b22601dd3e942fc240661c19b26f280508d2cedf

try to set the property persist.devcontrol.proximity with some value (I would propose 458 as I have on my phone)

**Comment by divis1969** [comment] 2016-09-16 12:47
I'm closing this issue.
If you will encounter an issue with the proximity property, please submit a new issue, I'l try to figure out why it is not working.

**Closed as completed by divis1969** 2016-09-16 12:47 UTC
